# Generated by Django 3.0.8 on 2020-10-08 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=255)),
                ('listing_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateField(default=datetime.datetime.now)),
                ('user_id', models.IntegerField(blank=True)),
                ('owner_id', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
