# Generated by Django 3.0.8 on 2020-10-15 23:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_favourites'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listing',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
