# Generated by Django 3.0.8 on 2020-10-15 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20201016_0104'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listing',
            managers=[
            ],
        ),
    ]
