# Generated by Django 3.1.2 on 2020-10-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20201016_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='username',
        ),
    ]
