# Generated by Django 3.1.2 on 2020-10-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_auto_20201022_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='username',
            new_name='owner',
        ),
    ]
