# Generated by Django 3.1.2 on 2020-12-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_auto_20201022_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Phones', 'Phones'), ('Tablets', 'Tablets'), ('Cars', 'Cars'), ('Motorbikes', 'Motorbikes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Vehicles', 'Vehicles')], max_length=255),
        ),
    ]
