# Generated by Django 3.1.2 on 2020-12-11 00:45

from django.db import migrations, models
import listing.validators


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_auto_20201204_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Adventure', 'Adventure'), ('Racing', 'Racing'), ('Sports', 'Sports'), ('Simulation', 'Simulation'), (
                'Consoles', 'Consoles'), ('Accessories', 'Accessories'), ('Services', 'Services'), ('Open World', 'Open World'), ('Farming & Industrial', 'Farming & Industrial'), ('Pets', 'Pets'), ('Jobs', 'Jobs')], max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.FileField(upload_to='photos/%Y/%m/%d', validators=[
                                   listing.validators.validate_file_size], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sub_category',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Car Accessories', 'Car Accessories'), ('Motorcycles and Scooters', 'Motorcycles and Scooters'), ('Trucks', 'Trucks'), ('Boats', 'Boats'), ('Caravans', 'Caravans'), ('Phones', 'Phones'), ('TV', 'TV'), ('Computer & Laptops', 'Computer & Laptops'), ('Gaming Consoles', 'Gaming Consoles'), ('Computer Hardware & Accessories', 'Computer Hardware & Accessories'), ('Cameras', 'Cameras'), ('Furniture and Decor', 'Furniture and Decor'), ('Homeware Appliances', 'Homeware Appliances'), ('Tools & DIY', 'Tools & DIY'), ('Garden & Braai', 'Garden & Braai'), ('Outdoor Equipment', 'Outdoor Equipment'), ('Bicycles', 'Bicycles'), ('Gym Fitness', 'Gym Fitness'), ('Houses & Flats for Rent', 'Houses & Flats for Rent'), ('Houses & Flats for Sale', 'Houses & Flats for Sale'), ('Land', 'Land'), ('Office Space', 'Office Space'), ('Vacation Rentals', 'Vacation Rentals'), ('Clothing & Shoes', 'Clothing & Shoes'), (
                'Jewellery & Accessories', 'Jewellery & Accessories'), ('Health, Beauty & Cosmetics', 'Health, Beauty & Cosmetics'), ('Toys & Games', 'Toys & Games'), ('Musical Instruments', 'Musical Instruments'), ('Art', 'Art'), ('Books, CDs, DVDs', 'Books, CDs, DVDs'), ('Construction', 'Construction'), ('Other Services', 'Other Services'), ('Event Services', 'Event Services'), ('Transport', 'Transport'), ('Repairs', 'Repairs'), ('Domestic Help', 'Domestic Help'), ('Prams & Cots', 'Prams & Cots'), ('Todler Clothing & Accessories', 'Todler Clothing & Accessories'), ('Farming Adventure', 'Farming Adventure'), ('Livestock', 'Livestock'), ('Farming Equipment', 'Farming Equipment'), ('Feeds, Supplements & Seeds', 'Feeds, Supplements & Seeds'), ('Dogs, Cats', 'Dogs, Cats'), ('Other Pets', 'Other Pets'), ('Pet Accessories', 'Pet Accessories'), ('Job Opportunities', 'Job Opportunities'), ('CVs & Resumes', 'CVs & Resumes')], default='empty', max_length=255),
        ),
    ]
