# Generated by Django 3.1.2 on 2020-12-11 00:51

from django.db import migrations, models
import listing.validators


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_auto_20201211_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', validators=[listing.validators.validate_file_size], verbose_name=''),
        ),
    ]
