# Generated by Django 3.1.2 on 2020-12-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_auto_20201211_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name=''),
        ),
    ]
